fix dejagnu detection with PKG_PATH set; problem reported by nick@ and others ok miod@

diff --git a/regress/gnu/egcs/libf2c/Makefile b/regress/gnu/egcs/libf2c/Makefile
--- a/regress/gnu/egcs/libf2c/Makefile
+++ b/regress/gnu/egcs/libf2c/Makefile
@@ -1,11 +1,9 @@
-# $OpenBSD: Makefile,v 1.5 2004/12/29 06:02:14 david Exp $
+# $OpenBSD: Makefile,v 1.6 2006/02/11 23:54:34 david Exp $
 
 .include <bsd.own.mk>
 
 NOMAN=
 NOPROG=
-
-HAVE_DEJAGNU!=pkg_info dejagnu
 
 .if ${USE_GCC3:L:Myes}
 TESTDIR=${BSDSRCDIR}/gnu/lib/libf2c
@@ -25,18 +23,16 @@ REGRESS_TARGETS=do-libf2c
 REGRESS_SKIP_TARGETS=do-libf2c
 .endif
 
-.if empty(HAVE_DEJAGNU)
-do-libf2c:
-	@echo "Error: DejaGnu is required to run this test.";
-	@echo "  You can install the package from the ftp site or compile it";
-	@echo "  from the ports tree (${PORTSDIR}/devel/dejagnu).";
-	@exit 1
-.else
 do-libf2c: 
+	@if [ ! "`pkg_info -e dejagnu-\*`" ]; then \
+	    echo "Error: DejaGnu is required to run this test."; \
+	    echo "  You can install the package from the ftp site or compile it"; \
+	    echo "  from the ports tree (${PORTSDIR}/devel/dejagnu)."; \
+	    exit 1; \
+	fi
 	@cd ${TESTDIR} && ${MAKE} -f Makefile.bsd-wrapper && \
 	cd ${TEST2DIR} && ${MAKE} -f Makefile.bsd-wrapper && \
 	cd ${TEST3DIR} && ${MAKE} G77DIR=${TEST4DIR} check RUNTEST=${RUNTEST};
-.endif
 
 .include <bsd.regress.mk>
 
diff --git a/regress/gnu/egcs/libiberty/Makefile b/regress/gnu/egcs/libiberty/Makefile
--- a/regress/gnu/egcs/libiberty/Makefile
+++ b/regress/gnu/egcs/libiberty/Makefile
@@ -1,9 +1,7 @@
-# $OpenBSD: Makefile,v 1.4 2004/12/29 06:02:14 david Exp $
+# $OpenBSD: Makefile,v 1.5 2006/02/11 23:54:34 david Exp $
 
 NOMAN=
 NOPROG=
-
-HAVE_DEJAGNU!=pkg_info dejagnu
 
 TESTDIR=${BSDSRCDIR}/gnu/lib/libiberty
 
@@ -13,17 +11,15 @@ REGRESS_TARGETS=do-libiberty
 REGRESS_SKIP_TARGETS=do-libiberty
 .endif
 
-.if empty(HAVE_DEJAGNU)
-do-libiberty:
-	@echo "Error: DejaGnu is required to run this test.";
-	@echo "  You can install the package from the ftp site or compile it";
-	@echo "  from the ports tree (${PORTSDIR}/devel/dejagnu).";
-	@exit 1
-.else
 do-libiberty: 
+	@if [ ! "`pkg_info -e dejagnu-\*`" ]; then \
+	    echo "Error: DejaGnu is required to run this test."; \
+	    echo "  You can install the package from the ftp site or compile it"; \
+	    echo "  from the ports tree (${PORTSDIR}/devel/dejagnu)."; \
+	    exit 1; \
+	fi
 	@cd ${TESTDIR} && ${MAKE} -f Makefile.bsd-wrapper && \
 	${MAKE} check RUNTEST=${RUNTEST};
-.endif
 
 .include <bsd.regress.mk>
 
