After the MANIFEST-based symbolic link creation loop, there is a check for a specific link to see if things worked out.  Add a check for the very last file in the MANIFEST, as well, since we are trying to spot a very odd bug where symbolic links are not being created.  Hopefully this will help us diagnose it. ok guenther millert

diff --git a/gnu/usr.bin/perl/Configure b/gnu/usr.bin/perl/Configure
--- a/gnu/usr.bin/perl/Configure
+++ b/gnu/usr.bin/perl/Configure
@@ -2756,6 +2756,10 @@ $define|true|[yY]*)
 				echo "Failed to create the symlinks (t/base/lex.t missing).  Aborting." >&4
 				exit 1
 			fi
+			if test ! -f x2p/walk.c; then
+				echo "Failed to create the symlinks (x2p/walk.c missing).  Aborting." >&4
+				exit 1
+			fi
 			cd UU
 			;;
 		*)	echo "(I cannot figure out how to do symbolic links, ignoring mksymlinks)." >&4
