Use vether instead of physical interfaces for temporary carp creation. Recommended by and discussed with many.

diff --git a/regress/usr.sbin/ifstated/ifstated b/regress/usr.sbin/ifstated/ifstated
--- a/regress/usr.sbin/ifstated/ifstated
+++ b/regress/usr.sbin/ifstated/ifstated
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $OpenBSD: ifstated,v 1.3 2017/07/31 18:41:21 rob Exp $
+# $OpenBSD: ifstated,v 1.4 2017/08/12 04:40:47 rob Exp $
 #/*
 # * Copyright (c) Rob Pierce <rob@2keys.ca>
 # *
@@ -31,6 +31,7 @@ SLEEP=10
 cleanup() {
 	ifconfig carp${VHIDA} destroy > /dev/null 2>&1
 	ifconfig carp${VHIDB} destroy > /dev/null 2>&1
+	ifconfig vether${VHIDB} destroy > /dev/null 2>&1
 	rm working/ifstated.conf >/dev/null 2>&1
 	rm working/ifstated.log >/dev/null 2>&1
 	rm working/output.test >/dev/null 2>&1
@@ -53,15 +54,15 @@ skip() {
 
 trap 'skip' INT
 
-# look for a suitable physical interface for carp
-NIC="$(netstat -rn -finet | grep ^default | awk '{ print $8 }')"
-STATUS="$(ifconfig | grep -A5 ^${NIC} | grep status: | awk '{ print $2 }')"
-
-if [ "$STATUS" != "active" ]
+ifconfig vether${VHIDB} create >/dev/null 2>&2
+if [ $? -ne 0 ]
 then
-	echo "No suitable physical interface found."
+	echo "Could not create temporary vether interface."
 	echo SKIPPED
 	exit 0
+else
+	ifconfig vether${VHIDB} up
+	NIC=vether${VHIDB}
 fi
 
 if [ "$(pgrep ifstated)" ]
