All mips tools should now configure with the same name (mipsel-unknown-openbsd) for little endian systems and (mips-unknown-openbsd) for big endian systems. gdb seems to work now but needs more testing.

diff --git a/gnu/usr.bin/binutils/gdb/configure b/gnu/usr.bin/binutils/gdb/configure
--- a/gnu/usr.bin/binutils/gdb/configure
+++ b/gnu/usr.bin/binutils/gdb/configure
@@ -2701,13 +2701,13 @@ configdirs="doc testsuite"
 frags=
 host_makefile_frag=${srcdir}/config/${gdb_host_cpu}/${gdb_host}.mh
 if test ! -f ${host_makefile_frag}; then
-{ echo "configure: error: "*** Gdb does not support host ${host}"" 1>&2; exit 1; }
+{ echo "configure: error: "*** Gdb does not support host ${host} ${host_makefile_frag}"" 1>&2; exit 1; }
 fi
 frags="$frags $host_makefile_frag"
 
 target_makefile_frag=${srcdir}/config/${gdb_target_cpu}/${gdb_target}.mt
 if test ! -f ${target_makefile_frag}; then
-{ echo "configure: error: "*** Gdb does not support target ${target}"" 1>&2; exit 1; }
+{ echo "configure: error: "*** Gdb does not support target ${target} ${target_makefile_frag}"" 1>&2; exit 1; }
 fi
 frags="$frags $target_makefile_frag"
 
