add a lot of /bin/sh before calling scripts like config.guess and so on - this way now the whole tree builds without requiring any file being executable (binutils was the last which required it) - now ctm -> cvs checkout -> make build works just fine (aside from other bugs in the source tree :-)

diff --git a/gnu/usr.bin/binutils/gdb/testsuite/gdb.threads/configure b/gnu/usr.bin/binutils/gdb/testsuite/gdb.threads/configure
--- a/gnu/usr.bin/binutils/gdb/testsuite/gdb.threads/configure
+++ b/gnu/usr.bin/binutils/gdb/testsuite/gdb.threads/configure
@@ -558,8 +558,8 @@ esac
 
 
 # Make sure we can run config.sub.
-if $ac_config_sub sun4 >/dev/null 2>&1; then :
-else { echo "configure: error: can not run $ac_config_sub" 1>&2; exit 1; }
+if /bin/sh $ac_config_sub sun4 >/dev/null 2>&1; then :
+else { echo "configure: error: can not run /bin/sh $ac_config_sub" 1>&2; exit 1; }
 fi
 
 echo $ac_n "checking host system type""... $ac_c" 1>&6
@@ -576,7 +576,7 @@ NONE)
   esac ;;
 esac
 
-host=`$ac_config_sub $host_alias`
+host=`/bin/sh $ac_config_sub $host_alias`
 host_cpu=`echo $host | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\1/'`
 host_vendor=`echo $host | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\2/'`
 host_os=`echo $host | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\3/'`
@@ -593,7 +593,7 @@ NONE)
   esac ;;
 esac
 
-target=`$ac_config_sub $target_alias`
+target=`/bin/sh $ac_config_sub $target_alias`
 target_cpu=`echo $target | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\1/'`
 target_vendor=`echo $target | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\2/'`
 target_os=`echo $target | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\3/'`
@@ -610,7 +610,7 @@ NONE)
   esac ;;
 esac
 
-build=`$ac_config_sub $build_alias`
+build=`/bin/sh $ac_config_sub $build_alias`
 build_cpu=`echo $build | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\1/'`
 build_vendor=`echo $build | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\2/'`
 build_os=`echo $build | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\3/'`
