use bsd.regress.mk framework and update dejagnu detection

diff --git a/regress/gnu/egcs/gcc/Makefile b/regress/gnu/egcs/gcc/Makefile
--- a/regress/gnu/egcs/gcc/Makefile
+++ b/regress/gnu/egcs/gcc/Makefile
@@ -1,9 +1,11 @@
-# $OpenBSD: Makefile,v 1.4 2004/07/21 04:28:49 david Exp $
+# $OpenBSD: Makefile,v 1.5 2004/12/29 06:02:14 david Exp $
 
 .include <bsd.own.mk>
 
 NOMAN=
 NOPROG=
+
+HAVE_DEJAGNU!=pkg_info dejagnu
 
 .if ${USE_GCC3:L:Myes}
 TESTDIR=${BSDSRCDIR}/gnu/usr.bin/gcc
@@ -11,22 +13,24 @@ TESTDIR=${BSDSRCDIR}/gnu/usr.bin/gcc
 TESTDIR=${BSDSRCDIR}/gnu/egcs/gcc
 .endif
 
-regress: 
-	@if ${RUNTEST} --help >/dev/null; then \
-	    if ${RUNTEST} --version|grep 'Framework version is.*1.3$$' >/dev/null; then \
-	    	echo "Error: you must have a dejagnu more recent than 1.3"; \
-		echo "For instance: ${PORTSDIR}/devel/dejagnu."; \
-	    else \
-		cd ${TESTDIR} && ${MAKE} -f Makefile.bsd-wrapper && \
-		    ${MAKE} check RUNTEST=${RUNTEST}; \
-	    fi; \
-	else \
-	    echo "Error: you must have a dejagnu more recent than 1.3 to run this test."; \
-	    echo "  You can install the package from the ftp site or recompile it"; \
-	    echo "  from the ports tree (${PORTSDIR}/devel/dejagnu)."; \
-	fi
+REGRESS_TARGETS=do-gcc
 
+.if !defined(DO_DEJATESTS)
+REGRESS_SKIP_TARGETS=do-gcc
+.endif
 
-.include <bsd.prog.mk>
+.if empty(HAVE_DEJAGNU)
+do-gcc: 
+	@echo "Error: DejaGnu is required to run this test.";
+	@echo "  You can install the package from the ftp site or compile it";
+	@echo "  from the ports tree (${PORTSDIR}/devel/dejagnu).";
+	@exit 1
+.else
+do-gcc: 
+	@cd ${TESTDIR} && ${MAKE} -f Makefile.bsd-wrapper && \
+	${MAKE} check RUNTEST=${RUNTEST};
+.endif
+
+.include <bsd.regress.mk>
 
 PORTSDIR?=/usr/ports
diff --git a/regress/gnu/egcs/libiberty/Makefile b/regress/gnu/egcs/libiberty/Makefile
--- a/regress/gnu/egcs/libiberty/Makefile
+++ b/regress/gnu/egcs/libiberty/Makefile
@@ -1,27 +1,30 @@
-# $OpenBSD: Makefile,v 1.3 2004/07/09 21:56:32 david Exp $
+# $OpenBSD: Makefile,v 1.4 2004/12/29 06:02:14 david Exp $
 
 NOMAN=
 NOPROG=
 
+HAVE_DEJAGNU!=pkg_info dejagnu
+
 TESTDIR=${BSDSRCDIR}/gnu/lib/libiberty
 
+REGRESS_TARGETS=do-libiberty
 
-regress: 
-	@if ${RUNTEST} --help >/dev/null; then \
-	    if ${RUNTEST} --version|grep 'Framework version is.*1.3$$' >/dev/null; then \
-	    	echo "Error: you must have a dejagnu more recent than 1.3"; \
-		echo "For instance: ${PORTSDIR}/devel/dejagnu."; \
-	    else \
-		cd ${TESTDIR} && ${MAKE} -f Makefile.bsd-wrapper && \
-		    ${MAKE} check RUNTEST=${RUNTEST}; \
-	    fi; \
-	else \
-	    echo "Error: you must have a dejagnu more recent than 1.3 to run this test."; \
-	    echo "  You can install the package from the ftp site or recompile it"; \
-	    echo "  from the ports tree (${PORTSDIR}/devel/dejagnu)."; \
-	fi
+.if !defined(DO_DEJATESTS)
+REGRESS_SKIP_TARGETS=do-libiberty
+.endif
 
+.if empty(HAVE_DEJAGNU)
+do-libiberty:
+	@echo "Error: DejaGnu is required to run this test.";
+	@echo "  You can install the package from the ftp site or compile it";
+	@echo "  from the ports tree (${PORTSDIR}/devel/dejagnu).";
+	@exit 1
+.else
+do-libiberty: 
+	@cd ${TESTDIR} && ${MAKE} -f Makefile.bsd-wrapper && \
+	${MAKE} check RUNTEST=${RUNTEST};
+.endif
 
-.include <bsd.prog.mk>
+.include <bsd.regress.mk>
 
 PORTSDIR?=/usr/ports
