perl 5.004_04

diff --git a/gnu/usr.bin/perl/ext/util/make_ext b/gnu/usr.bin/perl/ext/util/make_ext
--- a/gnu/usr.bin/perl/ext/util/make_ext
+++ b/gnu/usr.bin/perl/ext/util/make_ext
@@ -4,15 +4,34 @@
 # It primarily used by the perl Makefile:
 #
 # d_dummy $(dynamic_ext): miniperl preplibrary FORCE
-#        ext/util/make_ext dynamic $@
+# 	@sh ext/util/make_ext dynamic $@ MAKE=$(MAKE) LIBPERL_A=$(LIBPERL)
 #
 # It may be deleted in a later release of perl so try to
 # avoid using it for other purposes.
 
 target=$1;  shift
 extspec=$1; shift
+makecmd=$1; shift  # Should be something like MAKE=make
 passthru="$*" # allow extra macro=value to be passed through
 echo ""
+
+# Previously, $make was taken from config.sh.  However, the user might
+# instead be running a possibly incompatible make.  This might happen if
+# the user types "gmake" instead of a plain "make", for example.  The
+# correct current value of MAKE will come through from the main perl
+# makefile as MAKE=/whatever/make in $makecmd.  We'll be cautious in
+# case third party users of this script (are there any?) don't have the
+# MAKE=$(MAKE) argument, which was added after 5.004_03.
+case "$makecmd" in
+MAKE=*)
+	eval $makecmd
+	;;
+*)	echo 'ext/util/make_ext:  WARNING:  Please include MAKE=$(MAKE)'
+	echo '	in your call to make_ext.  See ext/util/make_ext for details.'
+	exit 1
+	;;
+esac
+
 
 case $CONFIG in
 '')
@@ -34,9 +53,9 @@ if test "X$extspec" = X; then
 fi
 
 # The Perl Makefile.SH will expand all extensions to
-#	lib/auto/X/X.a  (or lib/auto/X/Y/Y.a is nested)
+#	lib/auto/X/X.a  (or lib/auto/X/Y/Y.a if nested)
 # A user wishing to run make_ext might use
-#	X (or X/Y or X::Y is nested)
+#	X (or X/Y or X::Y if nested)
 
 # canonise into X/Y form (pname)
 case "$extspec" in
@@ -50,7 +69,6 @@ esac
 
 mname=`echo "$pname"   | sed -e 's!/!::!g'`
 depth=`echo "$pname"   | sed -e 's![^/][^/]*!..!g'`
-make=${altmake-make}
 makefile=Makefile
 makeargs=''
 makeopts=''
@@ -108,10 +126,10 @@ clean)		;;
 realclean)	;;
 *)	# Give makefile an opportunity to rewrite itself.
 	# reassure users that life goes on...
-	$make config $passthru || echo "$make config failed, continuing anyway..."
+	$MAKE config $passthru || echo "$MAKE config failed, continuing anyway..."
 	;;
 esac
 
-$make $makeopts $target $makeargs $passthru || exit
+$MAKE $makeopts $target $makeargs $passthru || exit
 
 exit $?
diff --git a/gnu/usr.bin/perl/os2/Makefile.SHs b/gnu/usr.bin/perl/os2/Makefile.SHs
--- a/gnu/usr.bin/perl/os2/Makefile.SHs
+++ b/gnu/usr.bin/perl/os2/Makefile.SHs
@@ -1,15 +1,44 @@
-# This file is read by Makefile.SH to produce rules for $(perllib)
-# We insert perl5.def since I do not know how to generate it yet.
+# This file is read by Makefile.SH to produce rules for $(LIBPERL) (and
+# some additional rules as well).
+
+# Rerun `sh Makefile.SH; make depend' after making any change.
+
+# Additional rules supported: perl_, aout_test, aout_install, use them
+# for a.out style perl (which may fork).
+
+$spitshell >>Makefile <<!GROK!THIS!
+
+AOUT_CCCMD	= \$(CC) $aout_ccflags $optimize
+AOUT_AR		= $aout_ar
+AOUT_OBJ_EXT	= $aout_obj_ext
+AOUT_LIB_EXT	= $aout_lib_ext
+AOUT_LIBPERL	= libperl$aout_lib_ext
+AOUT_CLDFLAGS	= $aout_ldflags
+
+AOUT_LIBPERL_DLL	= libperl_dll$aout_lib_ext
+AOUT_CCCMD_DLL	= \$(CC) -DDOSISH -DOS2=2 -DEMBED -I. -DPACK_MALLOC -DDEBUGGING_MSTATS -DTWO_POT_OPTIMIZE -DPERL_EMERGENCY_SBRK
+AOUT_CLDFLAGS_DLL	= -Zexe -Zmt -Zcrtdll
+
+LD_OPT		= $optimize
+
+!GROK!THIS!
 
 $spitshell >>Makefile <<'!NO!SUBS!'
-$(perllib): perl.imp perl.dll perl5.def
-	emximp -o $(perllib) perl.imp
+$(LIBPERL): perl.imp perl.dll perl5.def
+	emximp -o $(LIBPERL) perl.imp
+
+$(AOUT_LIBPERL_DLL): perl.imp perl.dll perl5.def
+	emximp -o $(AOUT_LIBPERL_DLL) perl.imp
 
 perl.imp: perl5.def
 	emximp -o perl.imp perl5.def
+	echo	'emx_calloc		emxlibcm	400	?' >> $@
+	echo	'emx_free		emxlibcm	401	?' >> $@
+	echo	'emx_malloc		emxlibcm	402	?' >> $@
+	echo	'emx_realloc		emxlibcm	403	?' >> $@
 
 perl.dll: $(obj) perl5.def perl$(OBJ_EXT)
-	$(LD) $(LDDLFLAGS) -o $@ perl$(OBJ_EXT) $(obj) -lsocket perl5.def
+	$(LD) $(LD_OPT) $(LDDLFLAGS) -o $@ perl$(OBJ_EXT) $(obj) $(libs) perl5.def
 
 perl5.def: perl.linkexp
 	echo "LIBRARY 'Perl' INITINSTANCE TERMINSTANCE"	> $@
@@ -19,8 +48,15 @@ perl5.def: perl.linkexp
 	echo DATA LOADONCALL NONSHARED MULTIPLE		>>$@
 	echo EXPORTS					>>$@
 	echo '  "ctermid"'				>>$@
+	echo '  "get_sysinfo"'				>>$@
 	echo '  "Perl_OS2_init"'			>>$@
 	echo '  "OS2_Perl_data"'			>>$@
+	echo '  "dlopen"'				>>$@
+	echo '  "dlsym"'				>>$@
+	echo '  "dlerror"'				>>$@
+	echo '  "my_tmpfile"'				>>$@
+	echo '  "my_tmpnam"'				>>$@
+	echo '  "my_flock"'				>>$@
 !NO!SUBS!
 
 if [ ! -z "$myttyname" ] ; then
@@ -35,25 +71,24 @@ $spitshell >>Makefile <<'!NO!SUBS!'
 #	grep -v '"\(malloc\|realloc\|free\)"' perl.linkexp	>>$@
 
 
-# We assume here that perl is available somewhere ...
-
 perl.exports: perl.exp EXTERN.h perl.h
-	(echo '#include "EXTERN.h"'; echo '#include "perl.h"' ; \
-			echo '#include "perl.exp"') | \
+	(echo "#include \"EXTERN.h\" \n#include \"perl.h\" \n#include \"perl.exp\"";	\
+	 echo "malloc\nrealloc\ncalloc\nfree") | \
 		$(CC) -DEMBED  -E - | \
 		awk '{if ($$2 == "") print $$1}' | sort | uniq > $@
-
-#		perl -ne 'print if (/^#!/ .. /^#\s/) && s/^(\w+) *$$/$$1/' > $@
 
 perl.linkexp: perl.exports perl.map
 	cat perl.exports perl.map | sort | uniq -d | sed -e 's/\w\+/  "\0"/' > perl.linkexp
 
-perl.map: $(obj) perl$(OBJ_EXT) miniperlmain$(OBJ_EXT)
-	$(CC) $(LARGE) $(CLDFLAGS) $(CCDLFLAGS) -o dummy.exe miniperlmain$(OBJ_EXT) perl$(OBJ_EXT) $(obj) -lsocket -lm -Zmap -Zlinker /map
-	awk '{if ($$3 == "") print $$2}' <dummy.map | sort | uniq > perl.map
-	rm dummy.exe dummy.map
+# We link miniperl statically, since .DLL depends on $(DYNALOADER) 
 
-depend: os2ish.h
+perl.map miniperl: $(obj) perl$(OBJ_EXT) miniperlmain$(OBJ_EXT)
+	$(CC) $(LARGE) $(CLDFLAGS) -o miniperl miniperlmain$(OBJ_EXT) perl$(OBJ_EXT) $(obj) $(libs) -Zmap -Zlinker /map
+	awk '{if ($$3 == "") print $$2}' <miniperl.map | sort | uniq > perl.map
+	rm miniperl.map
+	@./miniperl -w -Ilib -MExporter -e 0 || $(MAKE) minitest
+
+depend: os2ish.h dlfcn.h 
 
 # Stupid make? Needed...
 os2$(OBJ_EXT) : os2.c
@@ -61,11 +96,99 @@ os2$(OBJ_EXT) : os2.c
 os2.c: os2/os2.c os2ish.h
 	cp $< $@
 
+dl_os2.c: os2/dl_os2.c os2ish.h
+	cp $< $@
+
 os2ish.h: os2/os2ish.h
 	cp $< $@
+
+dlfcn.h: os2/dlfcn.h
+	cp $< $@
+
+# This one is compiled OMF, so cannot fork():
+
+perl___: $& perlmain$(OBJ_EXT) $(LIBPERL) $(DYNALOADER) $(static_ext) ext.libs
+	$(SHRPENV) $(CC) $(LARGE) $(CLDFLAGS) $(CCDLFLAGS) -o perl___ perlmain$(OBJ_EXT) $(DYNALOADER) $(static_ext) $(LIBPERL) `cat ext.libs` $(libs)
 
 installcmd : 
 	perl -e 'die qq{Give the option INSTALLCMDDIR=... to make!} if $$ARGV[0] eq ""' $(INSTALLCMDDIR)
 	perl os2/perl2cmd.pl $(INSTALLCMDDIR)
+
+# Aout section:
+
+aout_obj = $(addsuffix $(AOUT_OBJ_EXT),$(basename $(obj)))
+AOUT_DYNALOADER = $(addsuffix $(AOUT_LIB_EXT),$(basename $(DYNALOADER)))
+aout_static_ext = $(addsuffix $(AOUT_LIB_EXT),$(basename $(dynamic_ext)))
+aout_static_lib = $(addsuffix $(LIB_EXT),$(basename $(dynamic_ext)))
+
+aout_static_ext_dll = $(addsuffix $(AOUT_LIB_EXT),$(basename $(static_ext)))
+DYNALOADER_OBJ = ext/DynaLoader/DynaLoader$(OBJ_EXT)
+aout_static_ext_dll = $(addsuffix $(AOUT_LIB_EXT),$(basename $(static_ext)))
+AOUT_DYNALOADER_OBJ = $(addsuffix $(AOUT_OBJ_EXT),$(basename $(DYNALOADER_OBJ)))
+
+$(AOUT_DYNALOADER_OBJ) : $(DYNALOADER_OBJ)
+	emxaout -o $@ $<
+
+$(DYNALOADER_OBJ) : $(DYNALOADER)
+	@sh -c true
+
+$(AOUT_LIBPERL) : $(aout_obj) perl$(AOUT_OBJ_EXT)
+	rm -f $@
+	$(AOUT_AR) rcu $@ perl$(AOUT_OBJ_EXT) $(aout_obj)
+
+.c$(AOUT_OBJ_EXT):
+	$(AOUT_CCCMD) $(PLDLFLAGS) -c $*.c
+
+perlmain(AOUT_OBJ_EXT): perlmain.c
+	$(AOUT_CCCMD_DLL) $(PLDLFLAGS) -c perlmain.c
+
+aout_perlmain.c: miniperlmain.c config.sh makefile $(static_ext_autoinit)
+	sh writemain $(DYNALOADER) $(aout_static_lib) > tmp
+	sh mv-if-diff tmp aout_perlmain.c
+
+miniperl_: $& miniperlmain$(AOUT_OBJ_EXT) $(AOUT_LIBPERL) ext.libs
+	$(CC) $(LARGE) $(AOUT_CLDFLAGS) $(CCDLFLAGS) -o miniperl_ miniperlmain$(AOUT_OBJ_EXT) $(AOUT_LIBPERL) `cat ext.libs` $(libs)
+
+perl_: $& aout_perlmain$(AOUT_OBJ_EXT) $(AOUT_LIBPERL) $(AOUT_DYNALOADER) $(aout_static_ext) ext.libs
+	$(CC) $(LARGE) $(AOUT_CLDFLAGS) $(CCDLFLAGS) -o perl_ aout_perlmain$(AOUT_OBJ_EXT) $(AOUT_DYNALOADER) $(aout_static_ext) $(AOUT_LIBPERL) `cat ext.libs` $(libs)
+
+perl : perl__ perl___
+
+perl__: $& perlmain$(OBJ_EXT) $(LIBPERL) $(DYNALOADER) $(static_ext) ext.libs
+	$(CC) $(LARGE) $(CLDFLAGS) $(CCDLFLAGS) -o perl__ perlmain$(OBJ_EXT) $(DYNALOADER) $(static_ext) $(LIBPERL) `cat ext.libs` $(libs) -Zlinker /PM:PM
+
+# Forking dynamically loaded perl:
+
+perl: $& perlmain$(AOUT_OBJ_EXT) $(AOUT_DYNALOADER_OBJ) $(aout_static_ext_dll) $(AOUT_LIBPERL_DLL) ext.libs
+	$(CC) $(LARGE) $(AOUT_CLDFLAGS_DLL) $(CCDLFLAGS) -o perl perlmain$(AOUT_OBJ_EXT) $(AOUT_DYNALOADER_OBJ) $(aout_static_ext_dll) $(AOUT_LIBPERL_DLL) `cat ext.libs` $(libs)
+
+clean: aout_clean
+
+aout_clean:
+	-rm *perl_.* *.o *.a lib/auto/*/*.a ext/*/Makefile.aout
+
+aout_install: perl_ aout_install.perl
+
+aout_install.perl: perl_ installperl
+	./perl_ installperl
+
+aout_test: perl_
+	- cd t && (rm -f perl_$(EXE_EXT); $(LNS) ../perl_$(EXE_EXT) perl$(EXE_EXT)) && ./perl TEST </dev/tty
+
+lib/auto/OS2/*/%.a : ext/OS2/%/Makefile.aout
+	cd ext/OS2/$(basename $(notdir $@)) ; make -f Makefile.aout config || echo "$make config failed, continuing anyway..."
+	cd ext/OS2/$(basename $(notdir $@)) ; make -f Makefile.aout LINKTYPE=static CCCDLFLAGS=
+
+lib/auto/*/%.a : ext/%/Makefile.aout
+	cd ext/$(basename $(notdir $@)) ; make -f Makefile.aout config || echo "$make config failed, continuing anyway..."
+	cd ext/$(basename $(notdir $@)) ; make -f Makefile.aout LINKTYPE=static CCCDLFLAGS=
+
+.PRECIOUS : ext/%/Makefile.aout ext/OS2/%/Makefile.aout
+
+ext/OS2/%/Makefile.aout : miniperl_
+	cd $(dir $@) ; ../../../miniperl_ -I ../../../lib Makefile.PL MAKEFILE=Makefile.aout INSTALLDIRS=perl 
+
+ext/%/Makefile.aout : miniperl_
+	cd $(dir $@) ; ../../miniperl_ -I ../../lib Makefile.PL MAKEFILE=Makefile.aout INSTALLDIRS=perl 
 
 !NO!SUBS!
diff --git a/gnu/usr.bin/perl/x2p/Makefile.SH b/gnu/usr.bin/perl/x2p/Makefile.SH
--- a/gnu/usr.bin/perl/x2p/Makefile.SH
+++ b/gnu/usr.bin/perl/x2p/Makefile.SH
@@ -14,18 +14,22 @@ esac
 : This forces SH files to create target in same directory as SH file.
 : This is so that make depend always knows where to find SH derivatives.
 case "$0" in
-*/*) cd `expr X$0 : 'X\(.*\)/'` ;;
+*/Makefile.SH) cd `expr X$0 : 'X\(.*\)/'` ;;
+Makefile.SH) ;;
+*) case `pwd` in
+   */x2p) ;;
+   *) if test -d x2p; then cd x2p
+      else echo "Can't figure out where to write output."; exit 1
+	  fi;;
+   esac;;
 esac
 
 echo "Extracting x2p/Makefile (with variable substitutions)"
 rm -f Makefile
 cat >Makefile <<!GROK!THIS!
-# $RCSfile: Makefile.SH,v $$Revision: 1.1 $$Date: 1996/08/19 10:13:33 $
+# $RCSfile: Makefile.SH,v $$Revision: 4.1 $$Date: 92/08/07 18:29:07 $
 #
-# $Log: Makefile.SH,v $
-# Revision 1.1  1996/08/19 10:13:33  downsj
-# Initial revision
-#
+# $Log:	Makefile.SH,v $
 
 CC = $cc
 BYACC = $byacc
@@ -37,6 +41,10 @@ mallocobj = $mallocobj
 shellflags = $shellflags
 
 libs = $libs
+
+$make_set_make
+# grrr
+SHELL = $sh
 
 # These variables will be used in a future version to make
 # the make file more portable to non-unix systems.
@@ -72,7 +80,7 @@ plextract = find2perl s2p
 
 addedbyconf = $(shextract) $(plextract)
 
-h = EXTERN.h INTERN.h ../config.h handy.h hash.h a2p.h str.h util.h
+h = EXTERN.h INTERN.h ../config.h ../handy.h hash.h a2p.h str.h util.h
 
 c = hash.c $(mallocsrc) str.c util.c walk.c
 
@@ -80,11 +88,9 @@ obj = hash$(OBJ_EXT) $(mallocobj) str$(OBJ_EXT) util$(OBJ_EXT) walk$(OBJ_EXT)
 
 lintflags = -phbvxac
 
-# grrr
-SHELL = /bin/sh
 
 .c$(OBJ_EXT):
-	$(CCCMD) $*.c
+	$(CCCMD) -DPERL_FOR_X2P $*.c
 
 all: $(public) $(private) $(util)
 	touch all
@@ -106,7 +112,8 @@ run_byacc:	FORCE
 a2p.c: a2p.y
 	-@touch a2p.c
 
-a2p$(OBJ_EXT): a2p.c a2py.c a2p.h EXTERN.h util.h INTERN.h handy.h ../config.h str.h hash.h
+a2p$(OBJ_EXT): a2p.c a2py.c a2p.h EXTERN.h util.h INTERN.h \
+		../handy.h ../config.h str.h hash.h
 	$(CCCMD) $(LARGE) a2p.c
 
 clean:
@@ -125,7 +132,7 @@ lint:
 	lint $(lintflags) $(defs) $(c) > a2p.fuzz
 
 depend: $(mallocsrc) ../makedepend
-	sh ../makedepend
+	sh ../makedepend MAKE=$(MAKE)
 
 clist:
 	echo $(c) | tr ' ' '\012' >.clist
@@ -144,6 +151,7 @@ $(plextract):
 malloc.c: ../malloc.c
 	rm -f malloc.c
 	sed <../malloc.c >malloc.c \
+	    -e 's/"EXTERN.h"/"..\/EXTERN.h"/' \
 	    -e 's/"perl.h"/"..\/perl.h"/' \
 	    -e 's/my_exit/exit/'
 
