Latest from Cyclic Software

diff --git a/gnu/usr.bin/cvs/zlib/Makefile.in b/gnu/usr.bin/cvs/zlib/Makefile.in
--- a/gnu/usr.bin/cvs/zlib/Makefile.in
+++ b/gnu/usr.bin/cvs/zlib/Makefile.in
@@ -1,5 +1,5 @@
 # Makefile for zlib
-# Copyright (C) 1995-1996 Jean-loup Gailly.
+# Copyright (C) 1995-1998 Jean-loup Gailly.
 # For conditions of distribution and use, see copyright notice in zlib.h 
 
 srcdir     = @srcdir@
@@ -9,6 +9,7 @@ VPATH      = @srcdir@
 # To compile and test, type:
 #   ./configure; make test
 # The call of configure is optional if you don't have special requirements
+# If you wish to build zlib as a shared library, use: ./configure -s
 
 # To install /usr/local/lib/libz.* and /usr/local/include/zlib.h, type:
 #    make install
@@ -25,43 +26,78 @@ CFLAGS=@CFLAGS@
 
 LDFLAGS=@LDFLAGS@
 LDSHARED=$(CC)
+CPP=$(CC) -E
 
-VER=1.0.4
+VER=1.1.3
 LIBS=libz.a
+SHAREDLIB=libz.so
 
 # For CVS, separate AR and ARFLAGS.
 AR=ar
-RANLIB=ranlib
-TAR=tar
+RANLIB=@RANLIB@
+AMTAR=@AMTAR@
+SHELL=/bin/sh
 
 prefix=@prefix@
 exec_prefix = $(prefix)
+libdir = ${exec_prefix}/lib
+includedir = ${prefix}/include
 
 OBJS = adler32.o compress.o crc32.o gzio.o uncompr.o deflate.o trees.o \
        zutil.o inflate.o infblock.o inftrees.o infcodes.o infutil.o inffast.o
 
+OBJA =
+# to use the asm code: make OBJA=match.o
+
 TEST_OBJS = example.o minigzip.o
 
-# build_zlib.com added for CVS
-DISTFILES = README INDEX ChangeLog configure Makefile.*[a-z0-9] Make_vms.com \
-	    descrip.mms zlib.def zlib.rc algorithm.doc *.[ch] \
-	    build_zlib.com zlib.dsp .cvsignore
+DISTFILES = README FAQ INDEX ChangeLog configure Makefile.* *.[ch] *.mms \
+  algorithm.txt zlib.3 msdos/Make*[a-z0-9] msdos/zlib.def msdos/zlib.rc \
+  nt/Make*[a-z0-9] nt/zlib.dnt amiga/Make*.??? os2/M*.os2 os2/zlib.def \
+  contrib/RE*.contrib contrib/*.txt contrib/asm386/*.asm contrib/asm386/*.c \
+  contrib/asm386/*.bat contrib/asm386/zlibvc.d?? contrib/asm[56]86/*.?86 \
+  contrib/asm[56]86/*.S contrib/iostream/*.cpp \
+  contrib/iostream/*.h  contrib/iostream2/*.h contrib/iostream2/*.cpp \
+  contrib/untgz/Makefile contrib/untgz/*.c contrib/untgz/*.w32 \
+  contrib/minizip/[CM]*[pe] contrib/minizip/*.[ch] contrib/minizip/*.[td]?? \
+  contrib/delphi*/*.??? \
+  Make_vms.com .cvsignore
+
+# for CVS's distdir & Makefile targets
+subdir = zlib
 
 # For CVS, just build libz.a
 all: libz.a
 
-test: all
-	./example
-	echo hello world | ./minigzip | ./minigzip -d 
+# To reenable make test
+all-original: all minigzip example
+
+check test: all-original
+	@LD_LIBRARY_PATH=.:$(LD_LIBRARY_PATH) ; export LD_LIBRARY_PATH; \
+	echo hello world | ./minigzip | ./minigzip -d || \
+	  echo '		*** minigzip test FAILED ***' ; \
+	if ./example; then \
+	  echo '		*** zlib test OK ***'; \
+	else \
+	  echo '		*** zlib test FAILED ***'; \
+	fi
 
 # For CVS, use an explict rc after $(AR).
-libz.a: $(OBJS)
-	$(AR) rc $@ $(OBJS)
-	-@ ($(RANLIB) $@ || true) 2>/dev/null
+libz.a: $(OBJS) $(OBJA)
+	$(AR) rc $@ $(OBJS) $(OBJA)
+	-@ ($(RANLIB) $@ || true) >/dev/null 2>&1
 
-libz.so.$(VER): $(OBJS)
+match.o: match.S
+	$(CPP) match.S > _match.s
+	$(CC) -c _match.s
+	mv _match.o match.o
+	rm -f _match.s
+
+$(SHAREDLIB).$(VER): $(OBJS)
 	$(LDSHARED) -o $@ $(OBJS)
-	rm -f libz.so; ln -s $@ libz.so
+	rm -f $(SHAREDLIB) $(SHAREDLIB).1
+	ln -s $@ $(SHAREDLIB)
+	ln -s $@ $(SHAREDLIB).1
 
 example: example.o $(LIBS)
 	$(CC) $(CFLAGS) -o $@ example.o $(LDFLAGS) $(LIBS)
@@ -69,61 +105,122 @@ example: example.o $(LIBS)
 minigzip: minigzip.o $(LIBS)
 	$(CC) $(CFLAGS) -o $@ minigzip.o $(LDFLAGS) $(LIBS)
 
-# For CVS, remove the install and uninstall targets.
-install:
+# For CVS, make install dependant on all and remove the uninstall target.
+install: all
 uninstall:
 .PHONY: install uninstall
+
+# Remove targets for CVS
+info:
+installcheck:
+.PHONY: info installcheck
+
+#install: $(LIBS)
+#	-@if [ ! -d $(includedir)  ]; then mkdir $(includedir); fi
+#	-@if [ ! -d $(libdir) ]; then mkdir $(libdir); fi
+#	cp zlib.h zconf.h $(includedir)
+#	chmod 644 $(includedir)/zlib.h $(includedir)/zconf.h
+#	cp $(LIBS) $(libdir)
+#	cd $(libdir); chmod 755 $(LIBS)
+#	-@(cd $(libdir); $(RANLIB) libz.a || true) >/dev/null 2>&1
+#	cd $(libdir); if test -f $(SHAREDLIB).$(VER); then \
+#	  rm -f $(SHAREDLIB) $(SHAREDLIB).1; \
+#	  ln -s $(SHAREDLIB).$(VER) $(SHAREDLIB); \
+#	  ln -s $(SHAREDLIB).$(VER) $(SHAREDLIB).1; \
+#	  (ldconfig || true)  >/dev/null 2>&1; \
+#	fi
+# The ranlib in install is needed on NeXTSTEP which checks file times
+# ldconfig is for Linux
+
+#uninstall:
+#	cd $(includedir); \
+#	v=$(VER); \
+#	if test -f zlib.h; then \
+#	  v=`sed -n '/VERSION "/s/.*"\(.*\)".*/\1/p' < zlib.h`; \
+#          rm -f zlib.h zconf.h; \
+#	fi; \
+#	cd $(libdir); rm -f libz.a; \
+#	if test -f $(SHAREDLIB).$$v; then \
+#	  rm -f $(SHAREDLIB).$$v $(SHAREDLIB) $(SHAREDLIB).1; \
+#	fi
 
 installdirs:
 .PHONY: installdirs
 
-# mostlyclean added for CVS.
-clean mostlyclean:
-	rm -f *.o *~ example minigzip libz.a libz.so* foo.gz
-
-# distclean and realclean added for CVS.
-distclean realclean: clean
-	rm -f Makefile
-.PHONY: distclean realclean
-
-# dist-dir added for CVS.
-dist-dir:
-	mkdir ${DISTDIR}
-	for i in `cd $(srcdir); echo ${DISTFILES}`; do \
-	  ln $(srcdir)/$${i} ${DISTDIR}; \
+# distdir added for CVS.
+top_builddir = ..
+PACKAGE = @PACKAGE@
+VERSION = @VERSION@
+distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)
+distdir:
+	@d=$(srcdir); \
+	for file in `cd $$d; echo $(DISTFILES)`; do \
+	  if test -d $(distdir)/`dirname $$file`; then \
+	    :; \
+	  else \
+	    mkdir $(distdir)/`dirname $$file`; \
+	  fi; \
+	  if test -d $$d/$$file; then \
+	    cp -pR $$d/$$file $(distdir) \
+	    || exit 1; \
+	  else \
+	    test -f $(distdir)/$$file \
+	    || cp -p $$d/$$file $(distdir)/$$file \
+	    || exit 1; \
+	  fi; \
 	done
-.PHONY: dist-dir
+.PHONY: distdir
 
-# ls added for CVS.
-ls:
-	@echo $(DISTFILES)
-.PHONY: ls
+# mostlyclean added for CVS.
+mostlyclean clean:
+	rm -f *.o *~ example minigzip libz.a libz.so* foo.gz so_locations \
+	   _match.s maketree
+.PHONY: mostlyclean clean
+
+# distclean and realclean and maintainer-clean added for CVS.
+distclean realclean maintainer-clean:	clean
+	rm -f Makefile
+.PHONY: distclean realclean maintainer-clean
 
 zip:
 	mv Makefile Makefile~; cp -p Makefile.in Makefile
+	rm -f test.c ztest*.c contrib/minizip/test.zip
 	v=`sed -n -e 's/\.//g' -e '/VERSION "/s/.*"\(.*\)".*/\1/p' < zlib.h`;\
 	zip -ul9 zlib$$v $(DISTFILES)
 	mv Makefile~ Makefile
 
 dist:
 	mv Makefile Makefile~; cp -p Makefile.in Makefile
+	rm -f test.c ztest*.c contrib/minizip/test.zip
 	d=zlib-`sed -n '/VERSION "/s/.*"\(.*\)".*/\1/p' < zlib.h`;\
 	rm -f $$d.tar.gz; \
 	if test ! -d ../$$d; then rm -f ../$$d; ln -s `pwd` ../$$d; fi; \
 	files=""; \
 	for f in $(DISTFILES); do files="$$files $$d/$$f"; done; \
 	cd ..; \
-	GZIP=-9 $(TAR) chofz $$d/$$d.tar.gz $$files; \
+	GZIP=-9 $(AMTAR) chofz $$d/$$d.tar.gz $$files; \
 	if test ! -d $$d; then rm -f $$d; fi
 	mv Makefile~ Makefile
 
-tags:	
-	etags *.[ch]
+.PHONY: tags
+tags: TAGS
+
+TAGS:
+	tags=; \
+	here=`pwd`; \
+	list=`(echo *.[ch] && cd $(srcdir) && echo *.[ch]) |sort |uniq`; \
+	unique=`for i in $$list; do \
+	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
+	  done | \
+	  $(AWK) '    { files[$$0] = 1; } \
+	       END { for (i in files) print i; }'`; \
+	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
+	  || etags $(ETAGS_ARGS) $$tags $$unique $(LISP)
 
 # Makefile target added for CVS.
-subdir = zlib
-Makefile: ../config.status Makefile.in
-	cd .. && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= ./config.status
+Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
+	cd $(top_builddir) \
+	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
 depend:
 	makedepend -- $(CFLAGS) -- *.[ch]
@@ -145,6 +242,6 @@ inflate.o: zutil.h zlib.h zconf.h infblock.h
 inftrees.o: zutil.h zlib.h zconf.h inftrees.h
 infutil.o: zutil.h zlib.h zconf.h infblock.h inftrees.h infcodes.h infutil.h
 minigzip.o:  zlib.h zconf.h 
-trees.o: deflate.h zutil.h zlib.h zconf.h 
+trees.o: deflate.h zutil.h zlib.h zconf.h trees.h
 uncompr.o: zlib.h zconf.h
 zutil.o: zutil.h zlib.h zconf.h  
